"""The `users` table: one row per account. An account can be reached via
Telegram, via a username/password, or (once linked) both — `id` is the one
stable identity everything else (sessions, splits, order caches) is scoped
to; `telegram_id` and `username`/`password_hash` are optional, independent
ways to authenticate into that same row.

YC secrets and the password/recovery-code hashes are stored encrypted/hashed
at rest (see services/crypto.py, services/password_auth.py) — callers should
go through services/user_store.py rather than touching this model's raw
columns directly, so plaintext/hashes never leak outside that module.
"""

from datetime import datetime, timezone

from sqlalchemy import DateTime, Integer, LargeBinary, String
from sqlalchemy.orm import Mapped, mapped_column

from ..db import Base

# Reserved id for the pre-existing owner's account, created by
# scripts/migrate_legacy_env.py. Not a Telegram id (that column is left
# NULL) — this account logs in with the username/password chosen during
# migration. Real accounts get an autogenerated id starting at 1.
LEGACY_USER_ID = 0


def _utcnow() -> datetime:
    return datetime.now(tz=timezone.utc)


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)

    # Telegram identity — optional, unique when set.
    telegram_id: Mapped[int | None] = mapped_column(Integer, unique=True, nullable=True)
    telegram_username: Mapped[str | None] = mapped_column(String(128), nullable=True)
    photo_url: Mapped[str | None] = mapped_column(String(512), nullable=True)

    # Username/password identity — optional, unique when set.
    username: Mapped[str | None] = mapped_column(String(64), unique=True, nullable=True)
    password_hash: Mapped[str | None] = mapped_column(String(256), nullable=True)
    # Single-use; re-generated every time it's consumed by a forgot-password
    # reset, or on demand from an authenticated session.
    recovery_code_hash: Mapped[str | None] = mapped_column(String(256), nullable=True)

    # Shared profile fields regardless of login method.
    first_name: Mapped[str] = mapped_column(String(128), nullable=False, default="")
    last_name: Mapped[str | None] = mapped_column(String(128), nullable=True)
    email: Mapped[str | None] = mapped_column(String(256), nullable=True)  # optional, never verified

    yc_phone_local_enc: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)
    yc_phone_e164_enc: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)
    yc_device_id_enc: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)
    yc_jwt_enc: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)

    default_participants: Mapped[str] = mapped_column(String(512), nullable=False, default="Me")
    google_sheet_id: Mapped[str | None] = mapped_column(String(128), nullable=True)

    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=_utcnow)
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
